name: Haskell CI

on:
  push:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test-on-linux:
    strategy:
      matrix:
        ghc: ['8.10.7', '9.2.4']
      fail-fast: false

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Workaround runner image issue
      # https://github.com/actions/runner-images/issues/7061
      run: sudo chown -R $USER /usr/local/.ghcup
    - name: ghcup
      run: |
        ghcup install ghc ${{ matrix.ghc }}
        ghcup set ghc ${{ matrix.ghc }}
        ghcup install cabal latest
        ghcup set cabal latest

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: |
        export POSTGRES_PASSWORD=postgres
        cabal test all

  test-on-windows:
    strategy:
      matrix:
        ghc: ['8.10.7', '9.2.4']
      fail-fast: false

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: Add-Content $env:GITHUB_PATH $env:PGBIN
    - name: ghcup
      run: |
        ghcup install ghc ${{ matrix.ghc }}
        ghcup set ghc ${{ matrix.ghc }}
        ghcup install cabal latest
        ghcup set cabal latest

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
